---
version: '3.7'

services:
  bind9-service:
    image: log4shell-bind9-service
    hostname: bind9-service
    container_name: bind9-service
    ports:
      - 53:53/udp
    networks:
      log4shell-network:
        ipv4_address: 10.128.0.2
    volumes:
      - bind9-logs:/var/log/bind

  bind9-interface:
    image: log4shell-bind9-interface
    hostname: bind9-interface
    container_name: bind9-interface
    ports:
      - 80:80
    networks:
      log4shell-network:
        ipv4_address: 10.128.0.3
    volumes:
      - bind9-logs:/bind9-logs:ro
      - openldap-logs:/openldap-logs:ro
    depends_on:
      - bind9-service

  openldap-service:
    image: log4shell-openldap-service
    hostname: openldap-service
    container_name: openldap-service
    ports:
      - 389:389
    networks:
      log4shell-network:
        ipv4_address: 10.128.0.4
    volumes:
      - openldap-logs:/var/log/openldap
    depends_on:
      - bind9-service

  app-2.8.2-vulnerable:
    image: log4shell-app-2.8.2-vulnerable
    hostname: app-2.8.2-vulnerable
    container_name: app-2.8.2-vulnerable
    ports:
      - 8880:8080
    networks:
      log4shell-network:
        ipv4_address: 10.128.0.5
    depends_on:
      - bind9-service
    volumes:
      - ${PWD}/files/resolv.conf:/etc/resolv.conf

networks:
  log4shell-network:
    name: log4shell-network
    driver: bridge
    ipam:
      config:
        - subnet: 10.128.0.0/16
          ip_range: 10.128.0.0/16
          gateway: 10.128.0.1

volumes:
  bind9-logs:
  openldap-logs:
