---
version: '3.7'

services:
  zookeeper1:
    image: confluentinc/cp-zookeeper:6.0.0
    hostname: zookeeper1
    container_name: zookeeper1
    ports:
      - 2181:2181
    networks:
      - kafka
    environment:
      ZOOKEEPER_4LW_COMMANDS_WHITELIST: "*"
      ZOOKEEPER_ALLOW_ANONYMOUS_LOGIN: "yes"
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka1:
    image: confluentinc/cp-kafka:6.0.0
    hostname: kafka1-broker1
    container_name: kafka1-broker1
    depends_on:
      - zookeeper1
    ports:
      - 29092:29092
      - 23456:23456
    networks:
      - kafka
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper1:2181
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_ADVERTISED_LISTENERS=CLIENT://kafka1-broker1:9092,EXTERNAL://localhost:29092
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS=0
      - KAFKA_JMX_PORT=23456
      - KAFKA_INTER_BROKER_LISTENER_NAME=CLIENT

  kafka1-rest:
    image: confluentinc/cp-kafka-rest:6.0.0
    hostname: kafka1-rest
    container_name: kafka1-rest
    ports:
      - 38082:38082
    depends_on:
      - zookeeper1
      - kafka1
    networks:
      - kafka
    environment:
      - KAFKA_REST_BOOTSTRAP_SERVERS=CLIENT://kafka1-broker1:9092
      - KAFKA_REST_HOST_NAME=kafka1-rest
      - KAFKA_REST_LISTENERS=http://0.0.0.0:38082

  zookeeper2:
    image: confluentinc/cp-zookeeper:6.0.0
    hostname: zookeeper2
    container_name: zookeeper2
    ports:
      - 2182:2182
    networks:
      - kafka
    environment:
      ZOOKEEPER_4LW_COMMANDS_WHITELIST: "*"
      ZOOKEEPER_ALLOW_ANONYMOUS_LOGIN: "yes"
      ZOOKEEPER_CLIENT_PORT: 2182
      ZOOKEEPER_TICK_TIME: 2000

  kafka2:
    image: confluentinc/cp-kafka:6.0.0
    hostname: kafka2-broker1
    container_name: kafka2-broker1
    depends_on:
      - zookeeper2
    ports:
      - 29093:29093
      - 23457:23457
    networks:
      - kafka
    environment:
      - KAFKA_BROKER_ID=2
      - KAFKA_ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper2:2182
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_ADVERTISED_LISTENERS=CLIENT://kafka2-broker1:9093,EXTERNAL://localhost:29093
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS=0
      - KAFKA_JMX_PORT=23457
      - KAFKA_INTER_BROKER_LISTENER_NAME=CLIENT

  brooklin:
    image: brooklin
    hostname: brooklin
    container_name: brooklin
    depends_on:
      - kafka2
      - zookeeper2
    ports:
      - 32311:32311
    networks:
      - kafka

networks:
  kafka:
